---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-uno
  description: "2024-04-15T22:23:16.606Z-teram-a: app-uno"
  annotations:
    argocd/app-selector: "teram-a-gitops=app-uno"
    argocd/app-namespace: teram-a-gitops
    backstage.io/kubernetes-id: app-uno
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=app-uno'
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
