---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-uno
  description: "2024-04-16T13:58:48.280Z-team-a: app-uno"
  annotations:
    argocd/app-selector: "team-a-gitops=app-uno"
    argocd/app-namespace: team-a-gitops
    backstage.io/kubernetes-id: app-uno
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=app-uno'
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
