---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-uno
  description: "team-a: app-uno"
  annotations:
    argocd/app-selector: "team-a-gitops=app-uno"
    argocd/app-namespace: team-a-gitops
    backstage.io/kubernetes-id: app-uno
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/instance=app-uno"
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: app-uno-api
  description: The apis.app uno REST API
spec:
  type: openapi
  lifecycle: production
  owner: group:default/ops
  definition:
    $openapi: ./petstore.yaml
